### ISSUE TITLE
DocStruct.getAllChildrenByTypeAndMetadataType only works as expected if the last piece of metadata has the given type

### ISSUE THREAD

**Issue by mel-mason** [intranda/ugh#1]
If you pass in a metadataType, the result is dependent on the ordering of the metadata. If the last metadata  for a child has the required type, it returns that child. But https://github.com/intranda/ugh/blob/a020d1296600dda7464ba254119cc9480b77756d/ugh/src/ugh/dl/DocStruct.java#L400 resets mdTypeTestPassed to false if any subsequent metadata doesn't have the type.

I can work around this bug, but thought I'd flag it up in case it causes errors in future.

**Comment by SteffenHankiewicz** [comment]
Thanks for this comment. We look into this. 
Additionally we check if ugh gets even pushed through to github at all correctly.

**Comment by SteffenHankiewicz** [comment]
This issue is fixed now. Goobi never used this method so that we never noticed it. But thanks for this reported issue.
We now configure the git push to end up automatically in github too. This should be visible in the next minutes here.

**Comment by mel-mason** [comment]
Thanks!

**Comment by SteffenHankiewicz** [comment]
Now it pushed through here too. You can see the fix in this new version now here:
https://github.com/intranda/ugh/commit/699378f4e8598a2fa7249e2b3d6741bd0b11c2b1?diff=unified#diff-08e5e726492ded258e8a418e43ea715eL391

Can we close this now?

**Comment by mel-mason** [comment]
Sure
